name: "Continuous Create Deploy"
on:
    workflow_run:
        workflows: ["Deployment Workflow"]
        types:
            - completed
jobs:
    fetch_and_start_the_app:
        runs-on: self-hosted
        steps:
            - name: "Remove container book1"
              run: "sudo docker rm -f book1 || true"
            
            - name: "Get the code from Docker Hub"
              run: "sudo docker pull abatan/book1:newest"
            
            - name: "Run the image as a container"
              run: "sudo docker run -d -p 80:80 --name book1 abatan/book1:newest"